### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by atdyer**
@hokiespurs @KateBrodie 

Okay, I think I've got everything fixed up but please take a quick look through the code.

- Kept changes to MasterProcess, you guys did a good job there
- Moved runup line extraction and filter out of PreProcessLine, there was too much happening in that function and I think it's much cleaner now. Preprocessing is now only rectifying, filtering, and gridding.
- Moved runup line extraction parameters to the params file
- Pre-science plots are in the spot where Kate wanted them

Did I miss anything?

## DON'T FORGET: I moved stuff into the params file so you have to regenerate it for this code to work!!!!!!!!

Checkout this branch and set it off running. Once I get the okay that it's working I'll merge into dev.

@KateBrodie here are the commands to checkout on reggie:

```bash
git fetch origin
git checkout bug-fixes
```

### CODE REVIEW

**Comment by atdyer** [comment]
Ok, this all looks good to me.

**Comment by atdyer** [comment]
@KateBrodie 

Pro-tip: I'm still logged in on reggie, you should log me out and log back in as yourself :+1:

**Comment by KateBrodie** [comment]
@atdyer you should stop trying to blame conversations with yourself on me.

**Comment by atdyer** [comment]
:trollface:

**Comment by hokiespurs** [comment]
:+1:

**Comment by hokiespurs** [comment]
@atdyer, I think you're good to merge this if you want... may want to check with @KateBrodie to make sure it doesnt mess anything up on her end

**Comment by KateBrodie** [comment]
@atdyer, @hokiespurs....oh hmm i've made some more changes on this branch i
think. let me figure this out.

**Pull request merged**
